### ISSUE TITLE
Add support to GitHub Actions

### ISSUE THREAD

**Issue by guibranco** [mike-north/chrome-github-boxcutter#11]
It would be nice if we have support to GitHub actions, so we can navigate from `[some-action].yml` file to it's repository.

Example:

```
jobs:
  build:
    name: Build
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
```

The last line should be a link to: [actions/checkout@v2](https://github.com/actions/checkout)
